query {

    stats ( interval, filters ) {

        interval
        filters

        orderCount
        grossAmount
        netAmount

        recurringOrderCount
        recurringGrossAmount
        recurringNetAmount

        customerCount

        refundCount
        refundAmount

        averageRevenuePerDay
        averageRevenuePerCustomer
        averageRevenuePerOrder
    }

    summary ( interval, filters, groupBy, sortBy, limit ) {
        interval
        filters
        groupBy
        sortBy
        limit

        stats {
            grouping

            orderCount
            grossAmount
            netAmount

            customerCount

            refundCount
            refundAmount
        }
    }

    orders ( interval, filters, sortBy, first, after, limit ) {
        sortBy

        edges {
            cursor
            node {
                id
                type
                status
                orderDate

                customer {
                    id
                    name
                    avatar
                }

                geo {
                    city
                    state
                    country
                }

                items {
                    quantity
                    product {
                        ... on Product {
                        name
                        id
                        }
                        ... on ProductVariant {
                        name
                        id
                        }
                    }
                }

                netAmount
            }
        }
        pageInfo {
            endCursor
            hasNextPage
        }
        totalCount
    }

    products ( interval, filters, sortBy, first, after, limit ) {
        sortBy

        edges {
            cursor
            node {
                ... on Product {
                name
                id
                }
                ... on ProductVariant {
                name
                id
                }
            }
        }
        pageInfo {
            endCursor
            hasNextPage
        }
        totalCount
    }

    filters ( category ) {
        field
        name
        type
        valueList {
            name
            value
        }
    }

    facets ( category, interval, filters ) {
        name
        type
        field
        values {
            ... on FacetTerm {
                name
                value
                count
                children {
                    name
                    value
                }
            }

            ... on FacetNumericRange {
                name
                value
                count
                numStart: start
                numEnd: end
            }

            ... on FacetDateRange {
                name
                value
                count
                dateStart:start
                dateEnd:end
            }
        }
    }
}
